---
title: "Demographics"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(xtable)
library(janitor)
library(RSQLite)
```

ADNI demographics

```{r}
# Summarise
adnidata_summary <- adnidata %>%
  group_by(DX_bl) %>%
  summarise(n = length(subj),
            age = round(mean(AGE, na.rm = TRUE), digits = 1),
            gender = paste(length(PTGENDER[PTGENDER=="Male"]),
                           length(PTGENDER[PTGENDER=="Female"]),
                           sep = "/"),
            mmse = round(mean(MMSE, na.rm = TRUE), digits =1),
            moca = round(mean(MOCA, na.rm = TRUE), digits =1))
  
datatable(adnidata_summary)

adnidata_summary_xtable <- xtable(adnidata_summary)
print(adnidata_summary_xtable)
```

ADNI training dataset only

```{r}
adnidata <- read.table("../data/adni_train_corrected.csv", header = TRUE, sep = ",")

# Summarise
adnidata_summary <- adnidata %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = paste(round(mean(age, na.rm = TRUE), digits = 1),
                        paste("(", round(sd(age, na.rm = TRUE), digits = 1), ")", sep = "")),
            sex = paste(length(gender[gender=="Male"]),
                           length(gender[gender=="Female"]),
                           sep = "/"))
  
#datatable(adnidata_summary)

adnidata_summary_xtable <- xtable(adnidata_summary)
print(adnidata_summary_xtable,
      include.rownames = FALSE)

rm(list = c("adnidata",
            "adnidata_summary",
            "adnidata_summary_xtable"))
```

ADNI test dataset only
```{r}
adnidata <- read.table("../data/adni_test_corrected.csv", header = TRUE, sep = ",")

# Summarise
adnidata_summary <- adnidata %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = paste(round(mean(age, na.rm = TRUE), digits = 1),
                        paste("(", round(sd(age, na.rm = TRUE), digits = 1), ")", sep = "")),
            sex = paste(length(gender[gender=="Male"]),
                           length(gender[gender=="Female"]),
                           sep = "/"))
  
#datatable(adnidata_summary)

adnidata_summary_xtable <- xtable(adnidata_summary)
print(adnidata_summary_xtable,
      include.rownames = FALSE)

rm(list = c("adnidata",
            "adnidata_summary",
            "adnidata_summary_xtable"))

```

NACC demographics

```{r}
# import diagnoses
clinical_data_file = "../data/nacc_collatedResults.csv"
nacc_clindata = read.table(clinical_data_file, header = TRUE)

nacc_clindata_summary <- nacc_clindata %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = paste(round(mean(age, na.rm = TRUE), digits = 1),
                              paste("(", round(sd(age, na.rm = TRUE), digits = 1), ")", sep = "")),
            sex = paste(length(gender[gender=="Male"]),
                           length(gender[gender=="Female"]),
                           sep = "/"))

#datatable(nacc_clindata_summary)

nacc_clindata_summary_xtable <- xtable(nacc_clindata_summary)
print(nacc_clindata_summary_xtable,
      include.rownames = FALSE)
```

```{r}
diagnosis_map = list("Alzheimer's disease (AD)" = 'AD',
                 'Vascular brain injury or vascular dementia including stroke' = 'OD',
                 'Lewy body disease (LBD)' = 'OD', 
                 'Control' = 'Control', 
                 'Depression' = 'OND',
                 'Missing/unknown' = 'remove', ## <<---------- !
                 'Other neurologic, genetic, or infectious condition' = 'OND',
                 'Cognitive impairment for other specified reasons (i.e., written-in values)' = 'OND',
                 'Prion disease (CJD, other)' = 'OD', 
                 'FTLD, other' = 'OD', 
                 'Anxiety disorder' = 'OND',
                 'Corticobasal degeneration (CBD)' = 'OD',
                 'Cognitive impairment due to medications' = 'OND',
                 'Other psychiatric disease' = 'OND',
                 'Progressive supranuclear palsy (PSP)' = 'OD',
                 'Cognitive impairment due to systemic disease or medical illness' = 'OND',
                 'Traumatic brain injury (TBI)' = 'OND',
                 'Cognitive impairment due to alcohol abuse' = 'OND', 
                 'Bipolar disorder' = 'OND',
                 'Schizophrenia or other psychosis' = 'OND',
                 'FTLD with motor neuron disease (e.g., ALS)' = 'OD'
                )
```



```{r}
rm(list = c("nacc_clindata_summary",
            "nacc_clindata",
            "nacc_clindata_summary_xtable"))
```

UK biobank demographics

```{r}
# create sqlite connection
ukbb.db <- DBI::dbConnect(SQLite(),
                          "../data/ukb40183.db")

ukbb_data <- dbGetQuery(ukbb.db,
                        sql(paste("SELECT demogs.age, baseline.sex, baseline.eid, clinicaldata.visit",
                                  "FROM baseline",
                                  "JOIN demogs, clinicaldata",
                                  "ON baseline.eid = demogs.eid",
                                  "AND baseline.eid = clinicaldata.eid",
                                  "AND clinicaldata.eid = demogs.eid",
                                  "AND clinicaldata.visit = demogs.visit",
                                  #"WHERE clinicaldata.visit = '2'",
                                  "WHERE baseline.imaging = 1"))) %>%
    filter(visit <= 2) %>%
    group_by(eid) %>%
    filter(visit == max(visit))


ukbb_data_summary <- ukbb_data %>%
  summarise(n = length(eid),
            age = paste(round(mean(age, na.rm = TRUE) / 365.25, digits = 1),
                        paste("(", round(sd(age / 365.25, na.rm = TRUE), digits = 1), ")", sep = "")),
            sex = paste(length(sex[sex=="0"]),
                           length(sex[sex =="1"]),
                           sep = "/"))

ukbb_data_summary_xtable <- xtable(ukbb_data_summary)
print(ukbb_data_summary_xtable,
      include.rownames = FALSE)

rm(list = c("ukbb_data",
            "ukbb_data_summary",
            "ukbb_data_summary_xtable"))
```