---
title: "Investigating the correlations of phenotyper score with clinical data in the NACC data"
output: html_notebook
---

This will investigate the relationship between the mean phenotype scores and clinical scores in the NACC dataset.

```{r}
library(dplyr)
library(stringr)
library(ggplot2)
library(DT)
library(brms)
library(bayesplot)
library(tidybayes)
library(xtable)
library(janitor)
library(tidyr)

options(mc.cores = parallel::detectCores())
set.seed(5)
```

```{r}
# import diagnoses
clinical_data_file = "../data/nacc_collatedResults.csv"
clindata = read.table(clinical_data_file, header = TRUE)

clindata_summary <- clindata %>%
  group_by(diagnosis) %>%
  #summarise(n = length(subj)) %>%
  summarise(n = length(subj),
            age = paste(round(mean(age, na.rm = TRUE), digits = 1),
                              paste("(", round(sd(age, na.rm = TRUE), digits = 1), ")", sep = "")),
            sex = paste(length(gender[gender=="Male"]),
                           length(gender[gender=="Female"]),
                           sep = "/")) %>%
  adorn_totals("row")

datatable(clindata_summary)

clindata_summary_xtable <- xtable(clindata_summary)
print(clindata_summary_xtable)
```


```{r}
# remove volume and thickness measures
clindata <- clindata %>%
  dplyr::select(colnames(.)[!grepl("volume", names(.))]) %>%
  dplyr::select(colnames(.)[!grepl("thickness", names(.))])

# import results
# the '50' is the dropout results
results_file = "../results/latest_output_nacc_50.csv"
results = read.table(results_file, header = TRUE, sep = ",")
results <- results %>%
  mutate(subj = paste("sub-NACC", str_pad(nacc_id, width=6, side="left", pad="0"), sep = "")) %>%
  dplyr::select(-nacc_id)

# diagnosis groups

diagnosis_map = list('Alzheimer’s disease (AD)' = 'AD',
                     'Vascular brain injury or vascular dementia including stroke' = 'OD',
                     'Lewy body disease (LBD)' = 'OD', 
                     'Control' = 'Control', 
                     'Depression' = 'OND',
                     'Missing/unknown' = 'remove', ## <<---------- !
                     'Other neurologic, genetic, or infectious condition' = 'OND',
                     'Cognitive impairment for other specified reasons (i.e., written-in values)' = 'OND',
                     'Prion disease (CJD, other)' = 'OD', 
                     'FTLD, other' = 'OD', 
                     'Anxiety disorder' = 'OND',
                     'Corticobasal degeneration (CBD)' = 'OD',
                     'Cognitive impairment due to medications' = 'OND',
                     'Other psychiatric disease' = 'OND',
                     'Progressive supranuclear palsy (PSP)' = 'OD',
                     'Cognitive impairment due to systemic disease or medical illness' = 'OND',
                     'Traumatic brain injury (TBI)' = 'OND',
                     'Cognitive impairment due to alcohol abuse' = 'OND', 
                     'Bipolar disorder' = 'OND',
                     'Schizophrenia or other psychosis' = 'OND',
                     'FTLD with motor neuron disease (e.g., ALS)' = 'OD')

results <- results %>%
  left_join(clindata, by = "subj") %>%
  mutate(diagnosis = diagnosis_map[diagnosis]) %>%
  filter(diagnosis != "remove")

results$diagnosis <- factor(unlist(results$diagnosis),
                            levels = c("Control", "AD", "OD", "OND"))

rm(clindata)

results_summary <- results %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = paste(round(mean(age, na.rm = TRUE), digits = 1),
                              paste("(", round(sd(age, na.rm = TRUE), digits = 1), ")", sep = "")),
            sex = paste(length(gender[gender=="Male"]),
                           length(gender[gender=="Female"]),
                           sep = "/")) %>%
  adorn_totals("row")

datatable(results_summary)

results_summary_xtable <- xtable(results_summary)
print(results_summary_xtable, include.rownames = FALSE)
```

```{r}
# add column for AD-like positive/negative
results <- results %>%
  group_by(subj) %>%
  mutate(adlike = if (mean > 0.5) {"Positive"} else {"Negative"})

```

# MMSE

First we'll plot MMSE against the mean

```{r}
naccmmse <- results %>%
  filter(!is.na(nacmmse))

naccmmse_summary <- naccmmse %>%
  group_by(adlike) %>%
  summarise(n = length(subj),
            mmse = paste(round(mean(nacmmse), digits = 1),
                         " (", round(sd(nacmmse), digits = 1), ")",
                         sep = ""),
            age = round(mean(age, na.rm = TRUE), digits = 1),
            sex = paste(length(gender[gender == "Female"]),
                        length(gender[gender == "Male"]),
                        sep = "/"))

datatable(naccmmse_summary)
```
```{r}
p <- ggplot(naccmmse,
            aes(y = nacmmse,
                x = adlike,
                fill = adlike)) +
  geom_boxplot() +
  labs(y = clinscore_name) +
  theme(axis.title.x = element_blank(),
        legend.position = "None",
        axis.text = element_text(size = 20),
        axis.title = element_text(size = 20))

print(p)
```


```{r}
p_mmse <- ggplot(naccmmse, aes(x = mean, y = nacmmse, group = adlike, colour = adlike))
p_mmse <- p_mmse + geom_point() + geom_smooth(method = lm)
print(p_mmse)
```

```{r}
# Bayesian analysis
priors <- c(prior(cauchy(10, 10), class = "Intercept"), 
            prior(cauchy(0, 10), class = "b"), 
            prior(cauchy(0, 10), class = "sigma"))

cog_brms <- brm(nacmmse ~ adlike + age, 
                data = naccmmse, 
                iter = 5000, warmup = 1000, chains = 4, 
                prior = priors)

summary(cog_brms)


```


```{r}
summary_model <- summary(cog_brms)

cog_brms %>%
  spread_draws(b_adlikePositive) %>%
  ggplot(aes(x = b_adlikePositive)) +
  geom_density() +
  geom_vline(aes(xintercept = mean(b_adlikePositive)),
             colour = "blue",
             linetype = "dashed") +
  geom_vline(xintercept = summary_model$fixed[2,3],
             colour = "blue",
             linetype = "dashed") + 
  geom_vline(xintercept = summary_model$fixed[2,4],
             colour = "blue",
             linetype = "dashed")

```

```{r, fig.height=2.5, fig.width=6}
cog_brms_draws <- cog_brms %>%
  spread_draws(b_adlikePositive, b_Intercept)

mean_intercept = mean(cog_brms_draws$b_Intercept)
sd_control = sd(naccmmse[naccmmse$adlike == "Negative", "nacmmse"][["nacmmse"]]) * 0.1

cog_brms_draws %>%
  dplyr::select(b_adlikePositive, b_Intercept) %>%
  mutate(b_adlikePositive = mean_intercept + b_adlikePositive) %>%
  pivot_longer(cols = c(b_adlikePositive, b_Intercept)) %>%
  group_by(name) %>%
  median_qi(.width = c(.8, .95)) %>%
  ggplot(aes(y = name, x = value, xmin = .lower, xmax = .upper)) +
  geom_rect(xmin = mean_intercept - sd_control,
            xmax = mean_intercept + sd_control,
            ymin = 0, ymax = 3,
            fill = "cornsilk3") +
  geom_pointinterval() +
  geom_vline(xintercept = mean_intercept, linetype = "dashed", colour = "blue") +
  geom_vline(xintercept = mean_intercept + sd_control, linetype = "dashed", colour = "blue") +
  geom_vline(xintercept = mean_intercept - sd_control, linetype = "dashed", colour = "blue") +
  scale_y_discrete(labels = c("AD-like positive", "AD-like negative")) +
  labs(x = clinscore_name) +
  theme(axis.title.y = element_blank(),
        axis.text = element_text(size = 15),
        axis.title.x = element_text(size = 15))
```

```{r}
# z-score values
mean_age = mean(naccmmse$age)
sd_age = sd(naccmmse$age)
naccmmse$age <- (naccmmse$age - mean_age) / sd_age

mean_nacmmse = mean(naccmmse$nacmmse)
sd_nacmmse = sd(naccmmse$nacmmse)
naccmmse$nacmmse <- (naccmmse$nacmmse - mean_nacmmse) / sd_nacmmse

mean_mean = mean(naccmmse$mean)
sd_mean = sd(naccmmse$mean)
naccmmse$mean <- (naccmmse$mean - mean_mean) / sd_mean


# set priors
mmse_priors = c(set_prior("cauchy(0,1)", class = "b", coef = "age"),
                set_prior("cauchy(0,1)", class = "b", coef = "adlikePositive"),
                set_prior("cauchy(0,1)", class = "b", coef = "mean"),
                set_prior("cauchy(0,1)", class = "b", coef = "mean:adlikePositive"))

fit_mmse <- brm(nacmmse ~ mean * adlike + age,
                data = naccmmse,
                prior = mmse_priors,
                family = "skew_normal",
                iter = 5000,
                chains = 4,
                seed = 5)

fit_mmse_summary <- summary(fit_mmse)
fit_mmse_summary
```


```{r}
# Plot posteriors
fit_mmse %>%
  spread_draws(b_adlikePositive) %>%
  ggplot(aes(x = b_adlikePositive)) +
  geom_density() +
  geom_vline(aes(xintercept = mean(b_adlikePositive)),
             colour = "blue",
             linetype = "dashed") +
  geom_vline(xintercept = fit_mmse_summary$fixed[2,3],
             colour = "blue",
             linetype = "dashed") + 
  geom_vline(xintercept = fit_mmse_summary$fixed[2,4],
             colour = "blue",
             linetype = "dashed")



```

```{r}
posterior_plot <- mcmc_areas(posterior,
                  pars = get_variables(fit_mmse)[grepl("b_mean:", get_variables(fit_mmse))])
plot(fit_mmse)
print(posterior_plot)



```

## piecewise linear regression model

```{r}
pw_form <- bf(nacmmse ~  intercept + mean_slope * mean * step(change - mean) * adlike * age)

```

# MOCA

```{r}
clinscore = "naccmoca"
clinscore_name = "MoCA"

naccmoca <- results %>%
  filter(!is.na(naccmoca))

naccmoca_summary <- naccmoca %>%
  group_by(adlike) %>%
  summarise(n = length(subj),
            moca = paste(round(mean(naccmoca), digits = 1),
                         " (", round(sd(naccmoca), digits = 1), ")",
                         sep = ""),
            age = round(mean(age, na.rm = TRUE), digits = 1),
            sex = paste(length(gender[gender == "Female"]),
                        length(gender[gender == "Male"]),
                        sep = "/"))

datatable(naccmoca_summary)
```
```{r}
p <- ggplot(naccmoca,
            aes(y = naccmoca,
                x = adlike,
                fill = adlike)) +
  geom_boxplot() +
  labs(y = clinscore_name) +
  theme(axis.title.x = element_blank(),
        legend.position = "None",
        axis.text = element_text(size = 20),
        axis.title = element_text(size = 20))

print(p)
```


```{r}
p_mmse <- ggplot(naccmoca, aes(x = mean, y = naccmoca, group = adlike, colour = adlike))
p_mmse <- p_mmse + geom_point() + geom_smooth(method = lm)
print(p_mmse)
```

```{r}
# Bayesian analysis
priors <- c(prior(cauchy(10, 10), class = "Intercept"), 
            prior(cauchy(0, 10), class = "b"), 
            prior(cauchy(0, 10), class = "sigma"))

cog_brms <- brm(naccmoca ~ adlike + age, 
                data = naccmoca, 
                iter = 5000, warmup = 1000, chains = 4, 
                prior = priors)

summary(cog_brms)


```


```{r}
summary_model <- summary(cog_brms)

cog_brms %>%
  spread_draws(b_adlikePositive) %>%
  ggplot(aes(x = b_adlikePositive)) +
  geom_density() +
  geom_vline(aes(xintercept = mean(b_adlikePositive)),
             colour = "blue",
             linetype = "dashed") +
  geom_vline(xintercept = summary_model$fixed[2,3],
             colour = "blue",
             linetype = "dashed") + 
  geom_vline(xintercept = summary_model$fixed[2,4],
             colour = "blue",
             linetype = "dashed")

```

```{r, fig.height=2.5, fig.width=6}
cog_brms_draws <- cog_brms %>%
  spread_draws(b_adlikePositive, b_Intercept)

mean_intercept = mean(cog_brms_draws$b_Intercept)
sd_control = sd(naccmoca[naccmoca$adlike == "Negative", "naccmoca"][["naccmoca"]]) * 0.1

cog_brms_draws %>%
  dplyr::select(b_adlikePositive, b_Intercept) %>%
  mutate(b_adlikePositive = mean_intercept + b_adlikePositive) %>%
  pivot_longer(cols = c(b_adlikePositive, b_Intercept)) %>%
  group_by(name) %>%
  median_qi(.width = c(.8, .95)) %>%
  ggplot(aes(y = name, x = value, xmin = .lower, xmax = .upper)) +
  geom_rect(xmin = mean_intercept - sd_control,
            xmax = mean_intercept + sd_control,
            ymin = 0, ymax = 3,
            fill = "cornsilk3") +
  geom_pointinterval() +
  geom_vline(xintercept = mean_intercept, linetype = "dashed", colour = "blue") +
  geom_vline(xintercept = mean_intercept + sd_control, linetype = "dashed", colour = "blue") +
  geom_vline(xintercept = mean_intercept - sd_control, linetype = "dashed", colour = "blue") +
  scale_y_discrete(labels = c("AD-like positive", "AD-like negative")) +
  labs(x = clinscore_name) +
  theme(axis.title.y = element_blank(),
        axis.text = element_text(size = 15),
        axis.title.x = element_text(size = 15))
```

```{r}
# z-score values
mean_age = mean(naccmoca$age)
sd_age = sd(naccmoca$age)
naccmoca$age <- (naccmoca$age - mean_age) / sd_age

mean_naccmoca = mean(naccmoca$naccmoca)
sd_naccmoca = sd(naccmoca$naccmoca)
naccmoca$naccmoca <- (naccmoca$naccmoca - mean_naccmoca) / sd_naccmoca

mean_mean = mean(naccmoca$mean)
sd_mean = sd(naccmoca$mean)
naccmoca$mean <- (naccmoca$mean - mean_mean) / sd_mean


# set priors
mmse_priors = c(set_prior("cauchy(0,1)", class = "b", coef = "age"),
                set_prior("cauchy(0,1)", class = "b", coef = "adlikePositive"),
                set_prior("cauchy(0,1)", class = "b", coef = "mean"),
                set_prior("cauchy(0,1)", class = "b", coef = "mean:adlikePositive"))

fit_mmse <- brm(naccmoca ~ mean * adlike + age,
                data = naccmoca,
                prior = mmse_priors,
                family = "skew_normal",
                iter = 5000,
                chains = 4,
                seed = 5)

fit_mmse_summary <- summary(fit_mmse)
fit_mmse_summary
```


```{r}
# Plot posteriors
fit_mmse %>%
  spread_draws(b_adlikePositive) %>%
  ggplot(aes(x = b_adlikePositive)) +
  geom_density() +
  geom_vline(aes(xintercept = mean(b_adlikePositive)),
             colour = "blue",
             linetype = "dashed") +
  geom_vline(xintercept = fit_mmse_summary$fixed[2,3],
             colour = "blue",
             linetype = "dashed") + 
  geom_vline(xintercept = fit_mmse_summary$fixed[2,4],
             colour = "blue",
             linetype = "dashed")



```

```{r}
posterior_plot <- mcmc_areas(posterior,
                  pars = get_variables(fit_mmse)[grepl("b_mean:", get_variables(fit_mmse))])
plot(fit_mmse)
print(posterior_plot)

```

# Digit span forward

```{r}
digif <- results %>%
  filter(!is.na(digif))

digif_summary <- digif %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = round(mean(age, na.rm = TRUE), digits = 1),
            sex = paste(length(gender[gender == "Female"]),
                        length(gender[gender == "Male"]),
                        sep = "/"))

datatable(digif_summary)
```

```{r}
p_mmse <- ggplot(digif, aes(x = mean, y = digif, group = diagnosis, colour = diagnosis))
p_mmse <- p_mmse + geom_point() + geom_smooth(method = lm)
print(p_mmse)
```

# Digit span backwards 

```{r}
digib <- results %>%
  filter(!is.na(digib))

digib_summary <- digib %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = round(mean(age, na.rm = TRUE), digits = 1),
            sex = paste(length(gender[gender == "Female"]),
                        length(gender[gender == "Male"]),
                        sep = "/"))

datatable(digib_summary)
```

```{r}
p_mmse <- ggplot(digib, aes(x = mean, y = digib, group = diagnosis, colour = diagnosis))
p_mmse <- p_mmse + geom_point() + geom_smooth(method = lm)
print(p_mmse)
```

# Animal fluency

```{r}
animals <- results %>%
  filter(!is.na(animals))

animals_summary <- animals %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = round(mean(age, na.rm = TRUE), digits = 1),
            sex = paste(length(gender[gender == "Female"]),
                        length(gender[gender == "Male"]),
                        sep = "/"))

datatable(animals_summary)
```

```{r}
p_mmse <- ggplot(animals, aes(x = mean, y = animals, group = diagnosis, colour = diagnosis))
p_mmse <- p_mmse + geom_point() + geom_smooth(method = lm)
print(p_mmse)
```

# Trails B

```{r}
trialsb <- results %>%
  filter(!is.na(trialsb))

trialsb_summary <- trialsb %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = round(mean(age, na.rm = TRUE), digits = 1),
            sex = paste(length(gender[gender == "Female"]),
                        length(gender[gender == "Male"]),
                        sep = "/"))

datatable(trialsb_summary)
```

```{r}
p_mmse <- ggplot(trialsb, aes(x = mean, y = trialsb, group = diagnosis, colour = diagnosis))
p_mmse <- p_mmse + geom_point() + geom_smooth(method = lm)
print(p_mmse)
```

# WAIS

```{r}
wais <- results %>%
  filter(!is.na(wais))

wais_summary <- wais %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = round(mean(age, na.rm = TRUE), digits = 1),
            sex = paste(length(gender[gender == "Female"]),
                        length(gender[gender == "Male"]),
                        sep = "/"))

datatable(wais_summary)
```

```{r}
p_mmse <- ggplot(wais, aes(x = mean, y = wais, group = diagnosis, colour = diagnosis))
p_mmse <- p_mmse + geom_point() + geom_smooth(method = lm)
print(p_mmse)
```

# Boston naming task

```{r}
boston <- results %>%
  filter(!is.na(boston))

boston_summary <- boston %>%
  group_by(diagnosis) %>%
  summarise(n = length(subj),
            age = round(mean(age, na.rm = TRUE), digits = 1),
            sex = paste(length(gender[gender == "Female"]),
                        length(gender[gender == "Male"]),
                        sep = "/"))

datatable(boston_summary)
```

```{r}
p_mmse <- ggplot(boston, aes(x = mean, y = boston, group = diagnosis, colour = diagnosis))
p_mmse <- p_mmse + geom_point() + geom_smooth(method = lm)
print(p_mmse)
```